<?php
// $Id: emf_campaign_monitor.module,v 1.1 2009/10/28 18:59:01 davyvandenbremt Exp $

/**
 * @file
 * Drupal hooks
 *
 * @author Davy Van Den Bremt
 */

/**
 * Implementation of hook_menu().
 */
function emf_campaign_monitor_menu() {

  // settings
  $items['admin/settings/emf_campaign_monitor'] = array(
    'title' => 'Campaign Monitor',
    'description' => 'Configure Campaign Monitor settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('emf_campaign_monitor_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'emf_campaign_monitor.settings.inc',
  );

  return $items;
}

/**
 * Implementation of hook_emf_info().
 */
function emf_campaign_monitor_emf_info() {
  return array(
    'name' => 'Campaign Monitor',
    'file' => 'emf_campaign_monitor.api.inc',
  );
}