<?php

/**
 * Implementation of hook_perm().
 */
function u21_content_perm() {
  return array(
    'create region',
    'edit region',
    'delete region',
  );
}

/**
 * Implementation of hook_access().
 */
function u21_content_access($op, $node, $account = NULL) {
  if ($node instanceOf stdClass) {
    $type = $node->type;
  }
  else {
    $type = $node;
  }

  $permissions = array(
    'region' => array(
      'create' => 'create region',
      'update' => 'edit region',
      'delete' => 'delete region',
    ),
  );

  if (isset($permissions[$type][$op])) {
    return user_access($permissions[$type][$op], $account);
  }
}

function u21_content_node_info() {
  return array(
    'region' => array(
      'name' => t('Region'),
      'module' => 'u21_content',
      'description' => 'Defines a region e.g Aarhus',
      'title_label' => t('Region name'),
      'body_label' => FALSE,
    ),
  );
}

/**
 * Implementation of hook_views_api() {
 */
function u21_content_views_api() {
  return array(
    'api' => 2.0,
  );
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function u21_content_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * Tells CTools (and thus Panels) where to look for plugin code.
 */
function u21_content_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implementation of hook_theme().
 */
function u21_content_theme($existing, $type, $theme, $path) {
  return array(
    'u21_content_region_menu' => array(
      'arguments' => array('node' => NULL),
      'template' => 'u21_content_panels_content_region_menu',
      'preprocess functions' => array('u21_content_preprocess_region_menu'),
    ),
    'u21_content_google_maps' => array(
      'arguments' => array('node' => NULL, 'width' => NULL, 'height' => NULL, 'zoom' => NULL),
      'template' => 'u21_content_panels_content_google_maps',
      'preprocess functions' => array('u21_content_preprocess_google_maps'),
    ),
  );
}

/**
 * Preprocess hook for the region title and menu pane.
 */
function u21_content_preprocess_region_menu(&$variables) {
  $node = $variables['node'];

  // Set title
  $variables['title'] = t('U21 in @title', array('@title' => $node->title));

  // Load menu
  $tree = menu_tree_all_data($node->field_menu_ref[0]['value']);
  $variables['menu'] = menu_tree_output($tree);
}

function u21_content_preprocess_google_maps(&$variables, $hook) {
  $node = $variables['node'];
  $location = $node->location;

  $variables['title'] = check_plain($node->title);
  $variables['map'] = gmap_simple_map($location['latitude'],
                                      $location['longitude'],
                                      '',
                                      check_plain($node->title),
                                      $variables['zoom'],
                                      $variables['width'].'px',
                                      $variables['height'].'px');
}