<?php

// Plugin definition
$plugin = array(
  'title' => t('Three column 3-6-3 stacked'),
  'icon' => 'threecol_3_6_3_stacked.png',
  'theme' => 'threecol_3_6_3_stacked',
  'css' => 'threecol_3_6_3_stacked.css',
  'panels' => array(
    'top' => t('Top'),
    'left' => t('Left side'),
    'center' => t('Center column'),
    'right' => t('Right side'),
    'lower_left' => t('Lower left'),
    'lower_right' => t('Lower right')
  ),
);
