<?php

/**
 * Implementation of hook_content_default_fields().
 */
function spotboxes_content_default_fields() {
  $fields = array();

  // Exported field: field_spotbox_image
  $fields['spotbox-field_spotbox_image'] = array(
    'field_name' => 'field_spotbox_image',
    'type_name' => 'spotbox',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'imceimage',
    'required' => '0',
    'multiple' => '0',
    'module' => 'imceimage',
    'active' => '1',
    'imceimage_file_types' => 'png,jpg,jpeg',
    'widget' => array(
      'imceimage_file_types' => 'png,jpg,jpeg',
      'default_value' => array(
        '0' => array(
          'imceimage_path' => '',
          'imceimage_width' => '',
          'imceimage_height' => '',
          'imceimage_alt' => '',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Spotbox photo',
      'weight' => '-4',
      'description' => '',
      'type' => 'imceimage',
      'module' => 'imceimage',
    ),
  );

  // Exported field: field_spotbox_link
  $fields['spotbox-field_spotbox_link'] = array(
    'field_name' => 'field_spotbox_link',
    'type_name' => 'spotbox',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'link',
    'required' => '0',
    'multiple' => '0',
    'module' => 'link',
    'active' => '1',
    'attributes' => array(
      'target' => 'default',
      'rel' => '',
      'class' => '',
      'title' => '',
    ),
    'display' => array(
      'url_cutoff' => '80',
    ),
    'url' => 0,
    'title' => 'none',
    'title_value' => '',
    'enable_tokens' => 0,
    'validate_url' => 1,
    'widget' => array(
      'default_value' => array(
        '0' => array(
          'title' => '',
          'url' => '',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Link',
      'weight' => '-2',
      'description' => '',
      'type' => 'link',
      'module' => 'link',
    ),
  );

  // Exported field: field_spotbox_text
  $fields['spotbox-field_spotbox_text'] = array(
    'field_name' => 'field_spotbox_text',
    'type_name' => 'spotbox',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '1',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => '5',
      'size' => 60,
      'default_value' => array(
        '0' => array(
          'value' => '',
          'format' => '3',
          '_error_element' => 'default_value_widget][field_spotbox_text][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Spotbox text',
      'weight' => '-3',
      'description' => '',
      'type' => 'text_textarea',
      'module' => 'text',
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Link');
  t('Spotbox photo');
  t('Spotbox text');

  return $fields;
}
